# Generated by Django 4.0.5 on 2022-06-06 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('episodes', '0003_remove_episode_episode_path_episode_episode_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_reaction', models.CharField(choices=[('Like', 1), ('Love', 2), ('Sad', 3), ('Anger', 4)], max_length=100)),
                ('like_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='episodes.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
