# Generated by Django 3.1.7 on 2021-04-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
