# Generated by Django 3.1.7 on 2021-04-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0006_auto_20210422_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=320, verbose_name='profile picture'),
        ),
    ]
