# Generated by Django 3.1.7 on 2021-04-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0007_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='episodes_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='likes_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='views_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
