# Generated by Django 3.1.7 on 2021-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_auto_20210422_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='episodes_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='story',
            name='publishing_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
