# Generated by Django 3.1.7 on 2021-04-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0009_auto_20210422_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='likes_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='views_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
