# Generated by Django 3.1.7 on 2021-04-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0011_auto_20210422_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
