# Generated by Django 3.1.7 on 2021-04-25 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0012_story_story_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_reader',
            new_name='is_artist',
        ),
    ]
