# Generated by Django 4.0.4 on 2022-04-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='story_id',
            new_name='story',
        ),
    ]
